### ISSUE TITLE
Error: running openai models

### ISSUE THREAD

**Issue by sonigeez** [neuml/annotateai#7]
code

```
from annotateai import Annotate
annotate = Annotate(
  "gpt-4o"
)
annotate("https://arxiv.org/pdf/2005.11401")
```

Error 
```
python annotate.py
Traceback (most recent call last):
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/gpt-4o/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 860, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 967, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1482, in _raise_on_head_call_error
    raise head_call_error
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1374, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1294, in get_hf_file_metadata
    r = _request_wrapper(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 278, in _request_wrapper
    response = _request_wrapper(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 302, in _request_wrapper
    hf_raise_for_status(response)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6769ba5d-4f8fcf4441c89fa60f1f52bb;35fb73ba-9651-44f5-9950-5167a784b43d)

Repository Not Found for url: https://huggingface.co/gpt-4o/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bharat/pdf-ano/annotate.py", line 4, in <module>
    annotate = Annotate(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/annotateai/annotate.py", line 34, in __init__
    self.llm = LLM(llm)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/pipeline/llm/llm.py", line 39, in __init__
    self.generator = GenerationFactory.create(path, method, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/pipeline/llm/factory.py", line 41, in create
    return HFGeneration(path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/pipeline/llm/huggingface.py", line 26, in __init__
    self.llm = HFLLM(path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/pipeline/llm/huggingface.py", line 39, in __init__
    super().__init__(self.task(path, task, **kwargs), path, quantize, gpu, model, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/pipeline/llm/huggingface.py", line 160, in task
    task = Models.task(path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/txtai/models/models.py", line 240, in task
    config = AutoConfig.from_pretrained(path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1021, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 590, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 649, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/bharat/pdf-ano/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: gpt-4o is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

**Comment by davidmezzetti** [comment]
Hello. Not all methods are supported with the default install. You need the `txtai[pipeline-llm]` extras package or you can just `pip install litellm`. 

https://neuml.github.io/txtai/install/#pipeline

**Comment by davidmezzetti** [comment]
Closing this issue due to inactivity. Please re-open or open a new issue to continue the conversation.
